[package]
name = "custodian-password"
version = "0.0.0-dev.1"
description = "Password management simplified."
readme = "../README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/khonsulabs/custodian"
keywords = ["password", "authentication", "login", "pake", "opaque"]
categories = ["authentication"]
edition = "2018"

[dependencies]
argon2 = "0.2"
curve25519-dalek = "3"
generic-array = { version = "0.14", features = ["more_lengths"] }
opaque-ke = { package = "custodian-opaque", path = "../opaque", version = "0.6.0-pre.1", features = [
	"slow-hash"
] }
serde-big-array = { version = "0.3", features = ["const-generics"] }
sha2 = "0.9"
serde = { version = "1", features = ["derive"] }
thiserror = "1"

[dev-dependencies]
anyhow = "1"
bincode = "1"
