name: CI

on: [push]

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Audit
        run: |
          cargo audit -D warnings
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run unit tests
        run: |
          cargo test --workspace --all-targets --all-features --exclude custodian-opaque
      - name: Run doc tests
        run: |
          rustup toolchain install nightly --profile minimal --allow-downgrade
          cargo +nightly test --workspace --doc --all-features --exclude custodian-opaque
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install nightly Rust
        run: |
          rustup toolchain install nightly --profile minimal --component clippy --allow-downgrade
          rustup default nightly
      - name: Run Clippy
        continue-on-error: true
        run: |
          cargo clippy --workspace --all-targets --all-features --exclude custodian-opaque
      - name: Run rustdoc
        env:
          RUSTDOCFLAGS: -D warnings
        run: |
          cargo doc --no-deps --document-private-items --workspace --all-features --exclude custodian-opaque
  docs:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Docs
        run: |
          rustup install nightly --profile minimal
          cargo +nightly doc --no-deps --workspace --all-features --exclude custodian-opaque
      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: target/doc/
          git-config-name: kl-botsu
          git-config-email: botsu@khonsulabs.com
          target-folder: /main/
          clean: true

  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install code coverage requirements
        run: |
          rustup component add llvm-tools-preview
          rustup install nightly
          curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -
      - name: Run code coverage
        run: |
          cargo xtask generate-code-coverage-report

      - name: Deploy Coverage
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: coverage/
          git-config-name: kl-botsu
          git-config-email: botsu@khonsulabs.com
          target-folder: /coverage/
          clean: true

  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Rust Formatting
        continue-on-error: true
        run: |
          rustup toolchain install nightly --profile minimal --component rustfmt --allow-downgrade
          cargo +nightly fmt -- --check
      - name: Prettier
        run: |
          sudo npm install -g prettier prettier-plugin-toml
          npx prettier -l .
